In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World!")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [9]:
result

b'Hello World!'

In [10]:
a = tf.constant(10)
b = tf.constant(20)

In [11]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [12]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [13]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [14]:
result

30

In [15]:
const = tf.constant(10)

In [16]:
fill_mat = tf.fill((4, 4), 10)

In [17]:
myzeros = tf.zeros((4,4))

In [18]:
myones = tf.ones((4,4))

In [19]:
myrandn = tf.random_normal((4,4), mean = 0, stddev=1.0)

In [22]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [23]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [24]:
sess = tf.InteractiveSession()

In [25]:
for op in my_ops:
    print(sess.run(op))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 1.81650865 -1.37306941 -0.42051455  0.05964191]
 [ 0.2326666   0.50004917  0.5336833  -0.86471146]
 [-1.98360121  1.14548337 -1.30123341 -0.5158087 ]
 [ 1.04432452  0.20224412 -0.72550529 -0.09147026]]


[[ 0.02886248  0.02101421  0.90301001  0.70481527]
 [ 0.66190588  0.08584332  0.80415213  0.50849104]
 [ 0.07763541  0.78256488  0.57764828  0.25710022]
 [ 0.70082104  0.16803873  0.56837976  0.47226191]]




In [26]:
a = tf.constant([[1,2],
                 [3,4]])

In [27]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [30]:
b = tf.constant([[10], [100]])

In [31]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [32]:
result = tf.matmul(a, b)

In [33]:
sess.run(result)

array([[210],
       [430]])

In [34]:
result.eval()

array([[210],
       [430]])

In [35]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1 + n2

In [36]:
with tf.Session() as sess:
    result = sess.run(n3)

In [37]:
result

3

In [38]:
print(n3)

Tensor("add_5:0", shape=(), dtype=int32)


In [39]:
graph_one = tf.get_default_graph()

In [40]:
print(graph_one)

In [41]:
graph_two = tf.Graph()

In [42]:
print(graph_two)

In [43]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


In [44]:
print(graph_two is tf.get_default_graph())

False


## Placeholders

In [55]:
sess = tf.InteractiveSession()

In [56]:
my_tensor = tf.random_uniform((4,4),0,1)

In [57]:
my_tensor

<tf.Tensor 'random_uniform_3:0' shape=(4, 4) dtype=float32>

In [58]:
my_var = tf.Variable(initial_value=my_tensor)

In [59]:
print(my_var)

<tf.Variable 'Variable_1:0' shape=(4, 4) dtype=float32_ref>


In [60]:
init = tf.global_variables_initializer()

In [62]:
sess.run(init)

In [63]:
sess.run(my_var)

array([[ 0.36002111,  0.12725282,  0.06849301,  0.42567801],
       [ 0.27416563,  0.08325648,  0.40028059,  0.21966159],
       [ 0.54154527,  0.81694508,  0.22685814,  0.84387028],
       [ 0.74468136,  0.32600379,  0.42300892,  0.36454999]], dtype=float32)

In [64]:
ph = tf.placeholder(tf.float32)